/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "sys_clocks.h"
#include "lpuart.h"
#include "adc.h"
#include "tim.h"
#include "dma.h"


volatile uint16_t AdcAvg;
volatile uint16_t Volt_adc;

int main(void)
{
	SystemClockSetup();
	LPUART1_config();
	Adc_Init();
	Dma2AdcInit();
	Dma2AdcStart();
	AdcDmaStart();
	Tim6Init();
	Tim6Start();
	AdcResult();
	Dma2UartInit();
    while(1)
    {
    	if(minute == 1)
    	{
        	AdcAvg = AdcResultAvg();
        	Volt_adc = Adc_Volt_Read();
    		minute = 0;
        	SendStringDma("AVG: ");
        	SendNumberDma(AdcAvg);
        	SendStringDma("\r\n mV: ");
        	SendNumberDma(Volt_adc);
        	SendStringDma("\r\n");
    	}
    }
}









