/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "sys_clocks.h"
#include "led.h"
#include "SEG_7.h"
#include "button.h"
#include "lpuart.h"


LedPanel panelLED;

int main(void)
{
	SystemClockSetup();
	LedConf();
	Seg_7_Conf();
	button_init();
	LPUART1_config();
	SendString("\r\n\r\n\r\n\r\n\r\n===== MENU =====\r\nCommands:\r\nLedControl\r\n7SegControl\r\nJoyControl\r\n\r\n\r\n\r\n\r\n");
    while(1)
    {
    	LPUART1_Menu();
    }
}









