/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "sys_clocks.h"
#include "led.h"
#include "lpuart.h"
#include "adc.h"
#include "tim.h"

uint32_t Value_adc;
uint32_t Volt_adc;
LedPanel panelLED;



int main(void)
{

	SystemClockSetup();
	LedConf();
	LPUART1_config();
	//SendString("Hello\r\n");
	Adc_Init();
	//Value_adc = Adc_Read();
	Tim6Init();
	Tim6Start();


    while(1)
    {
    	Value_adc = Adc_Read();
    	Volt_adc = Adc_Volt_Read();


    	if(minute == 1)
    	{
    		minute = 0;
    		SendString("\r\n adc Value:\r\n");
          	SendNumber(Value_adc);
          	SendString("\r\n mV:\r\n");
            SendNumber(Volt_adc);
    	}


    }
}









